import { Button } from "@/components/ui/button";
import { Textarea } from "@/components/ui/textarea";
import { Play, Download, Settings } from "lucide-react";

const Optimizer = () => {
  return (
    <div className="min-h-screen bg-background">
      {/* Fixed Header */}
      <header className="h-16 border-b border-border flex items-center justify-between px-8 bg-background/80 backdrop-blur-sm sticky top-0 z-50">
        <div className="flex items-center gap-3">
          <div className="w-8 h-8 rounded bg-primary/10 flex items-center justify-center">
            <span className="text-primary font-bold text-sm">VR</span>
          </div>
          <h1 className="text-xl font-semibold text-foreground">VeriRL Optimizer</h1>
        </div>
        
        <nav className="flex items-center gap-6">
          <a href="/" className="text-sm text-text-secondary hover:text-primary transition-colors">
            Home
          </a>
          <a href="/optimizer" className="text-sm text-primary font-medium">
            Optimizer
          </a>
          <a href="/results" className="text-sm text-text-secondary hover:text-primary transition-colors">
            Results
          </a>
          <Button size="sm" variant="outline" className="border-border hover:border-primary/50">
            <Settings className="w-4 h-4 mr-2" />
            Settings
          </Button>
        </nav>
      </header>

      {/* Main Content - Two Column Layout */}
      <div className="flex gap-6 p-6 max-h-[calc(100vh-4rem)]">
        {/* Left Panel - Input */}
        <div className="w-[45%] flex flex-col gap-4 sticky top-20 h-fit">
          <div className="bg-card border border-border rounded-lg p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-foreground">Input Verilog</h2>
              <span className="text-xs text-text-tertiary font-mono">module_counter.v</span>
            </div>
            <Textarea
              placeholder="// Paste your Verilog code here&#10;module counter (&#10;  input clk,&#10;  input rst,&#10;  output reg [7:0] count&#10;);&#10;  &#10;  always @(posedge clk or posedge rst) begin&#10;    if (rst)&#10;      count <= 8'b0;&#10;    else&#10;      count <= count + 1;&#10;  end&#10;endmodule"
              className="min-h-[500px] font-mono text-sm bg-background border-border focus:border-primary resize-none"
            />
          </div>

          <div className="bg-card border border-border rounded-lg p-6">
            <h3 className="text-sm font-semibold text-foreground mb-4">Optimization Targets</h3>
            <div className="space-y-3">
              <label className="flex items-center gap-3 cursor-pointer">
                <input type="checkbox" className="w-4 h-4 accent-primary" defaultChecked />
                <span className="text-sm text-text-secondary">Power Reduction</span>
              </label>
              <label className="flex items-center gap-3 cursor-pointer">
                <input type="checkbox" className="w-4 h-4 accent-primary" defaultChecked />
                <span className="text-sm text-text-secondary">Timing Optimization</span>
              </label>
              <label className="flex items-center gap-3 cursor-pointer">
                <input type="checkbox" className="w-4 h-4 accent-primary" />
                <span className="text-sm text-text-secondary">Area Minimization</span>
              </label>
            </div>
          </div>
        </div>

        {/* Right Panel - Output */}
        <div className="flex-1 flex flex-col gap-4 overflow-y-auto">
          <div className="bg-card border border-border rounded-lg p-6">
            <div className="flex items-center justify-between mb-4">
              <h2 className="text-lg font-semibold text-foreground">Optimized Output</h2>
              <Button size="sm" variant="outline" className="border-border hover:border-primary/50">
                <Download className="w-4 h-4 mr-2" />
                Export
              </Button>
            </div>
            <div className="bg-background rounded border border-border p-4 min-h-[500px]">
              <pre className="font-mono text-sm text-text-secondary">
                {`// Optimized Verilog - 32% power reduction
// Generated by VeriRL Optimizer

module counter_opt (
  input clk,
  input rst,
  output reg [7:0] count
);
  
  // Clock gating optimization applied
  wire clk_gated;
  assign clk_gated = clk & ~rst;
  
  always @(posedge clk_gated) begin
    count <= count + 1;
  end
  
  always @(posedge rst) begin
    count <= 8'b0;
  end
  
endmodule`}
              </pre>
            </div>
          </div>

          <div className="grid grid-cols-3 gap-4">
            <div className="bg-card border border-border rounded-lg p-4">
              <div className="text-xs text-text-tertiary mb-1">Power Savings</div>
              <div className="text-2xl font-bold text-success">-32%</div>
            </div>
            <div className="bg-card border border-border rounded-lg p-4">
              <div className="text-xs text-text-tertiary mb-1">Timing</div>
              <div className="text-2xl font-bold text-info">+15%</div>
            </div>
            <div className="bg-card border border-border rounded-lg p-4">
              <div className="text-xs text-text-tertiary mb-1">Gate Count</div>
              <div className="text-2xl font-bold text-foreground">142</div>
            </div>
          </div>
        </div>
      </div>

      {/* Bottom Action Bar */}
      <div className="fixed bottom-0 left-0 right-0 h-18 bg-card border-t border-border flex items-center justify-center gap-4 px-8 shadow-elevated">
        <Button 
          size="lg" 
          className="h-12 px-8 bg-primary text-primary-foreground hover:bg-primary/90 font-semibold shadow-glow"
        >
          <Play className="w-4 h-4 mr-2" />
          Run Optimization
        </Button>
        <Button size="lg" variant="outline" className="h-12 px-6 border-border hover:border-primary/50">
          Reset
        </Button>
      </div>
    </div>
  );
};

export default Optimizer;
